### PR TITLE
CPUTESTRFC.md

### PR DESCRIPTION
**Pull request by drivver44**
## Summary

goal is to have a CPU test system so that players can better understand why they are lagging or not lagging while other are.

## Links

- [Full Rendered Proposal]()

- [Discussion Thread](https://github.com/beyond-all-reason/rfcs/discussions/13)

---

**Important: Do NOT comment on this PR. Please use the discussion thread linked above to provide feedback, as it provides branched discussions that are easier to follow. This also makes the edit history of the PR clearer.**

### CODE REVIEW

**Comment by Beherith** [comment]
Chobby can give a viable benchmark, and submit it to teiserver in a few hundred millisecs.

**Comment by Beherith** [comment]
Not taking into account how infeasible it is to test our wildly varying load with respect to modern cpus, which operate under TDP time limits, along with coupled cpu-gpu power budgets in laptop systems.

**Comment by drivver44** [comment]
kk
just wanted to move this here as to why it was rejected earlier in the "NEW LOBBY" channel

**Comment by Jazcash** [comment]
Mind creating a discussion and using that to discuss the proposal? Cheers

**Comment by Beherith** [comment]
I want to flesh this out a bit further, the goal needs to be more clearly defined:
`goal is to have a CPU test system so that players can better understand why they are lagging or not lagging while other are.`

Exactly what information, and when do you wish to convey to players? How does our current interface support/block or otherwise make this not convey the right information?

@Jazcash I clicked the above 'discussion thread' link, did I not use this correctly?

**Comment by drivver44** [comment]
discussion made it includes the conversation that occured in new lobby

**Comment by drivver44** [comment]
closing as this is being rejected  for documentation purposes this was created

**Pull request closed without merging**
